on:
  push:
    branches:
      - main
  
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Fetch tags
      - run: git fetch --force --tags
      
      # Set version environment
      - name: Set VERSION
        run: |
          git describe
          echo "YBFEED_VERSION=`git describe --tags`" >> $GITHUB_ENV

      # Build web ui
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: npm install
        working-directory: ./web/ui
      - run: npm run build
        working-directory: ./web/ui

      # Build docker image
      - uses: ko-build/setup-ko@v0.6
      - run: GOFLAGS="-ldflags=-X=main.version=$YBFEED_VERSION" ko build -B --platform all --sbom none ./cmd/ybfeed
        env:
          KO_DOCKER_REPO: ghcr.io/ybizeul